curl vignette2.wikia.nocookie.net/skylanders/images/1/1f/Senseis.png/revision/latest -o Senseis.png
curl vignette4.wikia.nocookie.net/skylanders/images/c/ce/Air_Strike_Icon.png/revision/latest -o Air_Strike_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/f/f3/AirSymbolSkylanders.png/revision/latest -o AirSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/9/92/Brawler_symbol.png/revision/latest -o Brawler_symbol.png
curl vignette1.wikia.nocookie.net/skylanders/images/7/72/Ambush_Icon.png/revision/latest -o Ambush_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/e/ee/LifeSymbolSkylanders.png/revision/latest -o LifeSymbolSkylanders.png
curl vignette4.wikia.nocookie.net/skylanders/images/b/bf/Knight_symbol.png/revision/latest -o Knight_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/f/f4/Aurora_Icon.png/revision/latest -o Aurora_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/c/cd/LightSymbolSkylanders.png/revision/latest -o LightSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/b/b5/Swashbuckler_symbol.png/revision/latest -o Swashbuckler_symbol.png
curl vignette3.wikia.nocookie.net/skylanders/images/8/87/Barbella_Icon.png/revision/latest -o Barbella_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/f/f8/EarthSymbolSkylanders.png/revision/latest -o EarthSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/f/fd/Sentinel_symbol.png/revision/latest -o Sentinel_symbol.png
curl vignette1.wikia.nocookie.net/skylanders/images/a/a8/Boom_Bloom_Icon.png/revision/latest -o Boom_Bloom_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/e/ee/LifeSymbolSkylanders.png/revision/latest -o LifeSymbolSkylanders.png
curl vignette2.wikia.nocookie.net/skylanders/images/f/f0/Ninja_symbol.png/revision/latest -o Ninja_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/e/ed/Buckshot_Icon.png/revision/latest -o Buckshot_Icon.png
curl vignette1.wikia.nocookie.net/skylanders/images/7/72/MagicSymbolSkylanders.png/revision/latest -o MagicSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/8/8e/Bowslinger_symbol.png/revision/latest -o Bowslinger_symbol.png
curl vignette3.wikia.nocookie.net/skylanders/images/2/24/Chain_Reaction_Icon.png/revision/latest -o Chain_Reaction_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/d/d7/TechSymbolSkylanders.png/revision/latest -o TechSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/b/b5/Swashbuckler_symbol.png/revision/latest -o Swashbuckler_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/0/0b/Chopscotch_Icon.png/revision/latest -o Chopscotch_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/1/18/UndeadSymbolSkylanders.png/revision/latest -o UndeadSymbolSkylanders.png
curl vignette2.wikia.nocookie.net/skylanders/images/3/39/Smasher_symbol.png/revision/latest -o Smasher_symbol.png
curl vignette1.wikia.nocookie.net/skylanders/images/c/ce/Ember_Icon.png/revision/latest -o Ember_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/9/9c/FireSymbolSkylanders.png/revision/latest -o FireSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/f/fd/Sentinel_symbol.png/revision/latest -o Sentinel_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/3/3f/Flare_Wolf_Icon.png/revision/latest -o Flare_Wolf_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/9/9c/FireSymbolSkylanders.png/revision/latest -o FireSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/3/35/Bazooker_symbol.png/revision/latest -o Bazooker_symbol.png
curl vignette3.wikia.nocookie.net/skylanders/images/7/75/King_Pen_Icon.png/revision/latest -o King_Pen_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/4/4f/WaterSymbolSkylanders.png/revision/latest -o WaterSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/9/92/Brawler_symbol.png/revision/latest -o Brawler_symbol.png
curl vignette3.wikia.nocookie.net/skylanders/images/1/1a/Mysticat_Icon.png/revision/latest -o Mysticat_Icon.png
curl vignette1.wikia.nocookie.net/skylanders/images/7/72/MagicSymbolSkylanders.png/revision/latest -o MagicSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/b/bc/Sorcerer_symbol.png/revision/latest -o Sorcerer_symbol.png
curl vignette3.wikia.nocookie.net/skylanders/images/f/f0/Pit_Boss_Icon.png/revision/latest -o Pit_Boss_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/1/18/UndeadSymbolSkylanders.png/revision/latest -o UndeadSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/b/bc/Sorcerer_symbol.png/revision/latest -o Sorcerer_symbol.png
curl vignette1.wikia.nocookie.net/skylanders/images/0/01/Ro-Bow_Icon.png/revision/latest -o Ro-Bow_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/d/d7/TechSymbolSkylanders.png/revision/latest -o TechSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/8/8e/Bowslinger_symbol.png/revision/latest -o Bowslinger_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/1/14/Starcast_Icon.png/revision/latest -o Starcast_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/9/98/DarkSymbolSkylanders.png/revision/latest -o DarkSymbolSkylanders.png
curl vignette2.wikia.nocookie.net/skylanders/images/f/f0/Ninja_symbol.png/revision/latest -o Ninja_symbol.png
curl vignette4.wikia.nocookie.net/skylanders/images/d/dc/Tidepool_Icon.png/revision/latest -o Tidepool_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/4/4f/WaterSymbolSkylanders.png/revision/latest -o WaterSymbolSkylanders.png
curl vignette2.wikia.nocookie.net/skylanders/images/7/75/Quickshot_symbol.png/revision/latest -o Quickshot_symbol.png
curl vignette4.wikia.nocookie.net/skylanders/images/d/d9/Tri-Tip_Icon.png/revision/latest -o Tri-Tip_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/f/f8/EarthSymbolSkylanders.png/revision/latest -o EarthSymbolSkylanders.png
curl vignette2.wikia.nocookie.net/skylanders/images/3/39/Smasher_symbol.png/revision/latest -o Smasher_symbol.png
curl vignette3.wikia.nocookie.net/skylanders/images/7/7c/Wild_Storm_Icon.png/revision/latest -o Wild_Storm_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/f/f3/AirSymbolSkylanders.png/revision/latest -o AirSymbolSkylanders.png
curl vignette4.wikia.nocookie.net/skylanders/images/b/bf/Knight_symbol.png/revision/latest -o Knight_symbol.png
curl vignette3.wikia.nocookie.net/skylanders/images/e/e1/Bad_Juju_Icon.png/revision/latest -o Bad_Juju_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/f/f3/AirSymbolSkylanders.png/revision/latest -o AirSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/b/b5/Swashbuckler_symbol.png/revision/latest -o Swashbuckler_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/e/e1/Blaster-Tron_Icon.png/revision/latest -o Blaster-Tron_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/c/cd/LightSymbolSkylanders.png/revision/latest -o LightSymbolSkylanders.png
curl vignette4.wikia.nocookie.net/skylanders/images/b/bf/Knight_symbol.png/revision/latest -o Knight_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/6/6b/Chompy_Mage_Icon.png/revision/latest -o Chompy_Mage_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/e/ee/LifeSymbolSkylanders.png/revision/latest -o LifeSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/3/35/Bazooker_symbol.png/revision/latest -o Bazooker_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/5/56/Dr._Krankcase_Icon.png/revision/latest -o Dr._Krankcase_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/d/d7/TechSymbolSkylanders.png/revision/latest -o TechSymbolSkylanders.png
curl vignette2.wikia.nocookie.net/skylanders/images/7/75/Quickshot_symbol.png/revision/latest -o Quickshot_symbol.png
curl vignette1.wikia.nocookie.net/skylanders/images/e/e7/Golden_Queen_Icon.png/revision/latest -o Golden_Queen_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/f/f8/EarthSymbolSkylanders.png/revision/latest -o EarthSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/b/bc/Sorcerer_symbol.png/revision/latest -o Sorcerer_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/3/36/Grave_Clobber_Icon.png/revision/latest -o Grave_Clobber_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/4/4f/WaterSymbolSkylanders.png/revision/latest -o WaterSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/9/92/Brawler_symbol.png/revision/latest -o Brawler_symbol.png
curl vignette3.wikia.nocookie.net/skylanders/images/9/94/Hood_Sickle_Icon.png/revision/latest -o Hood_Sickle_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/9/98/DarkSymbolSkylanders.png/revision/latest -o DarkSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/f/fd/Sentinel_symbol.png/revision/latest -o Sentinel_symbol.png
curl vignette4.wikia.nocookie.net/skylanders/images/0/05/Kaos_Icon.png/revision/latest -o Kaos_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/d/dc/KaosSymbolSkylanders.png/revision/latest -o KaosSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/a/ab/Kaos_symbol.png/revision/latest -o Kaos_symbol.png
curl vignette4.wikia.nocookie.net/skylanders/images/2/26/Pain-Yatta_Icon.png/revision/latest -o Pain-Yatta_Icon.png
curl vignette1.wikia.nocookie.net/skylanders/images/7/72/MagicSymbolSkylanders.png/revision/latest -o MagicSymbolSkylanders.png
curl vignette2.wikia.nocookie.net/skylanders/images/3/39/Smasher_symbol.png/revision/latest -o Smasher_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/4/47/Tae_Kwon_Crow_Icon.png/revision/latest -o Tae_Kwon_Crow_Icon.png
curl vignette4.wikia.nocookie.net/skylanders/images/9/9c/FireSymbolSkylanders.png/revision/latest -o FireSymbolSkylanders.png
curl vignette2.wikia.nocookie.net/skylanders/images/f/f0/Ninja_symbol.png/revision/latest -o Ninja_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/f/f3/Wolfgang_Icon.png/revision/latest -o Wolfgang_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/1/18/UndeadSymbolSkylanders.png/revision/latest -o UndeadSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/8/8e/Bowslinger_symbol.png/revision/latest -o Bowslinger_symbol.png
curl vignette4.wikia.nocookie.net/skylanders/images/c/c5/Crash_Bandicoot_Icon.png/revision/latest -o Crash_Bandicoot_Icon.png
curl vignette3.wikia.nocookie.net/skylanders/images/e/ee/LifeSymbolSkylanders.png/revision/latest -o LifeSymbolSkylanders.png
curl vignette1.wikia.nocookie.net/skylanders/images/9/92/Brawler_symbol.png/revision/latest -o Brawler_symbol.png
curl vignette2.wikia.nocookie.net/skylanders/images/3/35/Dr._Neo_Cortex_Icon.png/revision/latest -o Dr._Neo_Cortex_Icon.png
curl vignette2.wikia.nocookie.net/skylanders/images/d/d7/TechSymbolSkylanders.png/revision/latest -o TechSymbolSkylanders.png
curl vignette3.wikia.nocookie.net/skylanders/images/b/bc/Sorcerer_symbol.png/revision/latest -o Sorcerer_symbol.png
